In [1]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
import RNA


input_s = '..........(((...((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).)))))))))))))..'
input_2 = '....(((.((((...((((....))))(((((.((........))))))))))))))......((((((((((........).)))))))))........'
input_s = "(((.(((......))).)))"
# input_s = "((.)"



#16 bit u_ints:
# 8 chars per []


def encode(input_s):
  
    outputs = []
    
    sections = int(len(input_s)/8)+1
    
#     print (len(input_s), sections)
    for section in range(sections):
    
        c_input = input_s[section*8:section*8+8]
#         print (c_input)
        
        output = 0

        if c_input[-1] == "(":
            output = 0b01
        if c_input[-1] == ")":
            output = 0b10

        for char in reversed(c_input):           
            output = output << 2        
            if char == "(":
    #             print(i, "add", 0b01)
                output |= 0b01
            if char == ")":
    #             print(i, "add", 0b10)
                output |= 0b10
    #             output |= 2

        print ("o:", output, bin(output))
        outputs.append(output)

    
    return outputs



def decode(input, length):    
    output =  ["."]*length    
    for i in range(length):        
        if (input & 1):
            output[i] = "("
        if (input & 2):
            output[i] = ")"        
        input = input >> 2
#     print (output)    

    
# for (int a = 1; a <= 200; a += 1) {
#     if (pt_bool[a * 2]) {
#         if (pt_bool[a * 2 + 1]) {
#             stack[hx++] = a;
#             // s += '(';
#         } else {
#             j     = stack[--hx];
#             pt[a] = j;
#             pt[j] = a;
#             // s += ')';
#         }
#     }
# }
    

stack  = [0]*len(input_s)    
    
# def decode_pt(input, length, stack):
    
    
#     output = [0]*(length+1)
#     output[0] = length
    
#     stack_i = 0
    
#     for i in range(length):
# #         print (stack)
#         if (input & 1):
# #             output[i] = "("
#             stack[stack_i] = i
#             stack_i += 1
#         if (input & 2):
#             stack_i -= 1
#             j = stack[stack_i]
#             output[i+1] = j+1
#             output[j+1] = i+1
#         input = input >> 2
# #         break
    
#     return output


def decode_pt(input, length, stack):    
    
    output = [0]*(length+1)
    output[0] = length
    
    stack_i = 0
    
    current_input = input[0]
    
    for i in range(length):
        
        if (i!=0 and i%8==0):
            print ("now", int(i/8))
            current_input = input[int(i/8)]
        
#         print (stack)
        if (current_input & 1):
#             output[i] = "("
            stack[stack_i] = i
            stack_i += 1
        if (current_input & 2):
            stack_i -= 1
            j = stack[stack_i]
            output[i+1] = j+1
            output[j+1] = i+1
            

            
        current_input = current_input >> 2
#         break
    
    return output
    
    
    
# decode(output, len(input_s))
# 

output = encode(input_s)
print (encode(input_s))

pt = decode_pt(output, len(input_s), stack)    

# print (RNA.ptable_from_string(input_s))
print (input_s)
print (RNA.db_from_ptable(pt))

# pt = decode_pt(encode(input_2), len(input_2), stack)
# print (RNA.ptable_from_string(input_2))
# print (input_2)
# print (RNA.db_from_ptable(pt))


# # print (output)
# # print (f"{output:b}")

# print (bin(255))

# ..........(((...((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).)))))))))))))..
# ..........(((...((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).)))))))))))
            

o: 5397 0b1010100010101
o: 174080 0b101010100000000000
o: 680 0b1010101000
o: 5397 0b1010100010101
o: 174080 0b101010100000000000
o: 680 0b1010101000
[5397, 174080, 680]
now 1
now 2
(((.(((......))).)))
(((.(((......))).)))


In [32]:
input = np.array([
    np.array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, ]),
    np.array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, ]),
    np.array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, ]),
    np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, ]),
    np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,])  ])

input = np.array([
    np.array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, ]),
    np.array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, ]),
    np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, ]),
    
    
])


In [33]:
print(input)

[[0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 0]
 [0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]]


In [34]:
c = input.T @ input

In [35]:

print (c)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 2 2 2 1 2 2 2 2 2 2 2 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 3 3 2 1 3 3 3 3 3 3 3 1 1 2 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [0 2 2 1 0 2 2 2 2 2 2 2 0 0 2 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]]


In [ ]:
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 
0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 

In [16]:
# hash function for structures

# https://stackoverflow.com/questions/2624192/good-hash-function-for-strings

# size_t       result = 0;
# const size_t prime  = 31;
# for (size_t i = 0; i < s; ++i) { result = p[i] + (result * prime); }


input_s = '..........(((...((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).)))))))))))))..'

input_pt = RNA.ptable_from_string(input_s)
print (input_pt)

move_1 = (-11, -98)
move_2 = (-12, -97)
move_3 = (-13, -96)
move_4 = (2, 99)


import numpy as np

# counter = np.int8(0)
# one = np.int8(1)

# Robert Jenkins' 32 bit integer hash function
# https://gist.github.com/badboy/6267743#:~:text=Knuth's%20Multiplicative%20Method&text=The%20key%20is%20multiplied%20by,to%20produce%20a%20hash%20result.&text=Bad%20hash%20results%20are%20produced,digits%20of%20the%20multiplication%20result.

def int_hash(a):
   a = (a+0x7ed55d16) + (a<<12);
   a = (a^0xc761c23c) ^ (a>>19);
   a = (a+0x165667b1) + (a<<5);
   a = (a+0xd3a2646c) ^ (a<<9);
   a = (a+0xfd7046c5) + (a<<3);
   a = (a^0xb55a4f09) ^ (a>>16);
   return a



def gen_hash(input_s):
    current_hash = np.uint32(1) # randomize to get a different result every time if collision fails?

    for i, j in moves:    
        input_s = list(input_s) # strings are not mutable...
        if i<0:
            # i = -i
            # j = -j
            input_s[-i-1] = '.'
            input_s[-j-1] = '.'
        else:
            input_s[i] = '('
            input_s[j] = ')'

        # move_hash = 17*i + 31*j
        source_1 = np.uint32(i)
        source_2 = np.uint32(j)

        # move_hash = 131*source_1;
        # move_hash += (move_hash << 10);
        # move_hash ^= (move_hash >> 6);

        # move_hash += 31*abs(source_2);
        # move_hash += (move_hash << 8);
        # move_hash ^= (move_hash >> 4);

        # move_hash ^= 17*abs(source_2);
        # move_hash += (move_hash << 10);
        # move_hash ^= (move_hash >> 6);

        move_hash = int_hash(source_1)
        move_hash += int_hash(abs(source_2))
        move_hash += int_hash(source_1*abs(source_2))

        current_hash = current_hash + move_hash
        # current_hash = current_hash + hash

        input_s = ''.join(input_s)
        
        # print (i, j, current_hash, move_hash)
        print (input_s, i, j, current_hash, move_hash)


moves = [move_1, move_2, move_3, move_4]
gen_hash(input_s)
moves = [move_4, move_3, move_2, move_1]
gen_hash(input_s)

(100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98, 97, 96, 0, 0, 0, 95, 94, 93, 92, 91, 90, 0, 0, 89, 88, 87, 86, 0, 49, 48, 47, 0, 45, 44, 43, 0, 0, 0, 0, 0, 0, 36, 35, 34, 0, 32, 31, 30, 0, 0, 0, 84, 83, 82, 0, 78, 77, 76, 0, 0, 0, 0, 0, 75, 74, 73, 0, 0, 0, 0, 0, 67, 66, 65, 59, 58, 57, 0, 0, 0, 55, 54, 53, 0, 28, 27, 26, 25, 22, 21, 20, 19, 18, 17, 13, 12, 11, 0, 0)
...........((...((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).))))))))))))... -11 -98 5362774864806857608 5362774864806857607
............(...((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).))))))))))).... -12 -97 -7721194324362644189 5362774884540049819
................((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).))))))))))..... -13 -96 -2358418775751934870 5362775548610709319
..(.............((((((..((((.(((.(((......))).)))...(((.(((.....(((.....))))))...))).))))))))))....) 2 99 -2356993052662271765 1425723089663105
..(.......(((...((((((..((((.(((.(((......)))

In [86]:
def detect_local_minimum(fc, structure):
    # perform gradient walk from sample to determine direct local minimum
    pt = RNA.IntVector(RNA.ptable(structure))
    fc.path(pt, 0, RNA.PATH_DEFAULT | RNA.PATH_NO_TRANSITION_OUTPUT)
    return RNA.db_from_ptable(list(pt))

In [88]:
add_moves = {(87, 96), (86, 97)}
s = "(((((((((.(.....(........)((...)).......(((....)))..........).)))))))))...(((((.(...((.((....)))).).)))))..((((....))))."

add_moves = {(61, 72), (64, 69), (8, 78), (9, 77), (20, 49), (12, 74), (11, 75), (-4, -72), (-1, -75), (10, 76), (62, 71), (-5, -71), (63, 70), (-2, -74), (-6, -70), (-7, -69)}
s = "((.((((((............(((....((.....))......))).(...((....))...)...)))))).))....."

add_moves = {(61, 72), (5, 15), (64, 69), (20, 49), (21, 48), (57, 77), (60, 74), (-4, -72), (-1, -75), (62, 71), (6, 14), (63, 70), (7, 13), (-2, -74), (59, 75), (58, 76)}
s = "((.((((((............(((....((.....))......))).(...((....))...)...)))))).))....."


sequence = "GAAAGUUUUCAAGAAAGUAAUAUAGUGUCCCAGUCAGGGGGUAGUGGCGCGUUCUGGACGCAUAGUAUUC"


add_moves = {(17, 68), (36, 53), (-30, -57), (29, 57), (16, 69)}
s = "(........).........(((((((((.((((...(.(.((....)).).).)))))))).)).))).."

sequence = 'UAAGGAAACUGAUGAGGGCAAAGUCUCUUCAUUGGCGCAAAACGGGGUAGAUGUCGGCCUGCAGGUGAUGAUGUAUCCGUCCGGCGAUCAACGCCUAAUUCGCAUCUCUUUAGGGUAUGA'
s = "........((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).)))))))....((.....)).((((...........))))......."
add_moves = {(37, 43), (36, 44), (4, 82), (-42, -80), (6, 80), (5, 81)}

In [89]:
fc = RNA.fold_compound(sequence)

pt = list(RNA.ptable_from_string(s))
l = RNA.loopidx_from_ptable(pt)


# move = (87, 96)
# move = (86, 97)




def remove_incompatible_bps(pt, l, i, j):
    i = abs(i)
    j = abs(j)
    # print ("adj1", RNA.db_from_ptable(pt))

    adjusted_bps = 0
    if (l[i] != l[j] or pt[i] != 0 or pt[j] != 0):
        
        if pt[i] != 0:
            b = pt[i]
            pt[b] = 0
            pt[i] = 0
            adjusted_bps += 1

        if pt[j] != 0:
            b = pt[j]
            pt[b] = 0
            pt[j] = 0
            adjusted_bps += 1
        
        # print ("adj2", RNA.db_from_ptable(pt), i, j)

        # update loop table
        l = RNA.loopidx_from_ptable(pt)
        
        # if we're still incompatible, move in
        if (l[i] != l[j]):      
            if (i+2 == j-1):
                adjusted_bps += remove_incompatible_bps(pt, l, i+1, j)
            else:
                adjusted_bps += remove_incompatible_bps(pt, l, i+1, j-1)
                
    return adjusted_bps
        
    
                     
temp_pt = list(RNA.ptable_from_string(s))

print (s, add_moves)

l = RNA.loopidx_from_ptable(temp_pt)
adjusted_bps = 0
# en_base = fc.eval_structure_pt(temp_pt)
for i,j in add_moves:
    adjusted_bps += remove_incompatible_bps(temp_pt, l, i, j)
    
for i,j in add_moves:
    if i>0:
        temp_pt[i] = j
        temp_pt[j] = i
    else:
        temp_pt[-i] = 0
        temp_pt[-j] = 0
        
# en_adj = fc.eval_structure_pt(temp_pt)
# s = RNA.db_from_ptable(temp_pt)
# en_improvement.append(en_adj-en_base)
# en_improvement_inc.append(adjusted_bps)

# print (s, adjusted_bps)
# print ("--")

........((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).)))))))....((.....)).((((...........))))....... {(-42, -80), (5, 81), (4, 82), (37, 43), (6, 80), (36, 44)}


In [90]:
for i,j in add_moves:
    temp_pt = list(RNA.ptable_from_string(s))
    en_base = fc.eval_structure_pt(temp_pt)
    
    # if its a direct move it should not count...
    adjusted_bps = remove_incompatible_bps(temp_pt, l, i, j)
    
    if i>0:
        temp_pt[i] = j
        temp_pt[j] = i
    else:
        temp_pt[-i] = 0
        temp_pt[-j] = 0
    
    en_adj = fc.eval_structure_pt(temp_pt)
    s_adj = RNA.db_from_ptable(temp_pt)
    print (s, en_base)
    print (s_adj, en_adj, i, j)
    
print ("(((....))).........(((((((((.((((..((.(.((....)).).)))))))))).)).))).. [  36,   53 ] -10.00")

........((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).)))))))....((.....)).((((...........))))....... -1760
........((((((((((.......)))))))))).......((((.((.((((((.((....)))))).)).)))))).....((.....)).((((...........))))....... -1630 -42 -80
........((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).)))))))....((.....)).((((...........))))....... -1760
....(...((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).))))))))...((.....)).((((...........))))....... -1350 5 81
........((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).)))))))....((.....)).((((...........))))....... -1760
...(....((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).))))))).)..((.....)).((((...........))))....... -1390 4 82
........((((((((((.......))))))))))......(((((.((.((((((.((....)))))).)).)))))))....((.....)).((((...........))))....... -1760
........((((((((((.......)))))))))).(.....)(((.((.((((((.((....)))))).)).)))))......((.....))

In [104]:
s = "...(((..((((((((((.......))))))))))((.....))((.((.((((((.((....)))))).)).))))..)))..((.....)).((((...........))))......."
temp_pt = list(RNA.ptable_from_string(s))
en_base = fc.eval_structure_pt(temp_pt)
print (s, en_base)
    
s = detect_local_minimum(fc, s)

temp_pt = list(RNA.ptable_from_string(s))
en_adj = fc.eval_structure_pt(temp_pt)
print (s_adj, en_adj)

...(((..((((((((((.......))))))))))((.....))((.((.((((((.((....)))))).)).))))..)))..((.....)).((((...........))))....... -1140
........((((((((((.......))))))))))(.......)((.((.((((((.((....)))))).)).)))).......((.....)).((((...........))))....... -1470
